name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls

      - run: "composer global require hirak/prestissimo"
      - run: "composer install"
      - name: Check Code
        uses: ducla5/laravel-app-reviewdog-action@v1
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
