name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          
      - name: Cache vendor folder
        id: cache-vendor
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - run: ls

      - name: Run composer install
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: "composer install"

      - run: ls
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - run: ls
