name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls

      - name: Run composer
        uses: nick-zh/composer-php@master
        with:
          action: 'install'
          options: ''

      - run: ls
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - run: ls
