name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest

    env:
      cache_version: 2 # increment to flush all caches

    steps:
      - uses: actions/checkout@v2
      - run: ls

      - uses: MilesChou/composer-action@master
        with:
          args: install --ignore-platform-reqs

      - run: ls
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - run: ls
