name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: "composer install"
      - run: ls
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
      - run: ls
