name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls

      - run: "composer global require hirak/prestissimo"
      - run: "composer install"

      - run: ls
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - run: ls
