name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run composer
        uses: nick-zh/composer-php@master
        with:
          action: 'install'

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
