name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "composer global require hirak/prestissimo"
      - run: "composer install"
      - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
